### ISSUE TITLE
Implement a better Build.Exclude

### ISSUE THREAD

**Issue by pauby** [psake/PowerShellBuild#42]
The `Build.Exclude` configuration is simply an array of strings passed to the `Get-ChildItem -Exclude` parameter. This is very inflexible and ... a little rubbish. If you try and exclude anything but file(s) it doesn't work.

## Expected Behavior

We should implement a `Build.ExcludePattern` and / or `Build.ExcludeWildcard` that allows the exclusion to match on a regular expression or wildcards.

The names above are just examples.

## Current Behavior

The `Build.Exclude` configuration is simply an array of strings passed to the `Get-ChildItem -Exclude` parameter. This is very inflexible and ... a little rubbish. If you try and exclude anything but file(s) it doesn't work.

## Possible Solution

I'm happy to submit a PR for this but looking to get agreement on the specifics above.

## Your Environment
* Module version used: 0.4.0
* Operating System and PowerShell version: Windows 10, PowerShell Core 7.0.0

**Comment by devblackops** [comment]
@pauby Since `Exclude` is treated as an array of regex patterns when `Compile` is `$true`, how about we make the behavior consistent when it's `$false` as well? We can take that same logic and use `Get-ChildItem` and exclude matches instead of `Copy-Item`?

Thoughts?

**Comment by pauby** [comment]
> Since Exclude is treated as an array of regex patterns when `Compile is $true`

I didn't actually know that. Just checked it out and indeed it is! What is even more embarrassing is that I [added it](https://github.com/psake/PowerShellBuild/pull/41/files). Brain. Gone.

I agree that is the best option and makes it consistent.

**Comment by Plork** [comment]
At the moment it seems broken as well tbh.

When you don't pass any 'exclude' its an empty array.

![image](https://user-images.githubusercontent.com/4212271/86097535-19a03c80-bab5-11ea-95d0-a7e8c7cd83f6.png)

So for each regex in this aray it checks for a '-notmatch'. But since the array is 0 it never checks for anything.

So before this little "hack" my "AllScripts" contains 2 files and after this it contains 0.

Before loop
![image](https://user-images.githubusercontent.com/4212271/86097705-59672400-bab5-11ea-94b2-93a11337f1b5.png)

After loop
![image](https://user-images.githubusercontent.com/4212271/86097762-700d7b00-bab5-11ea-82e7-68c17c2be3c6.png)
